apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-ratings
    projectName: {{ .Values.labels.projectName }}
  name: deploy-ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-ratings
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-ratings
    spec:
      containers:
      - image: {{ .Values.image.repo}}/ratings:{{ .Values.image.version}}
        name: ratings
        ports:
        - containerPort: 80
        resources: {}
status: {}
