apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-cart
    projectName: {{ .Values.labels.projectName }}
  name: deploy-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-cart
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-cart
    spec:
      containers:
      - image: {{ .Values.image.repo }}/cart:{{ .Values.image.version }}
        name: cart
        ports:
        - containerPort: 8080
        resources: {}
status: {}
