apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-catalogue
    projectName: {{ .Values.labels.projectName }}
  name: deploy-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-catalogue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-catalogue
    spec:
      containers:
      - image: {{ .Values.image.repo }}/catalogue:{{ .Values.image.version }}
        name: catalogue
        ports:
        - containerPort: 8080
        resources: {}
status: {}
