apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-web
    projectName: {{ .Values.labels.projectName }}
  name: deploy-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-web
    spec:
      containers:
      - image: {{ .Values.image.repo }}/web:{{ .Values.image.version }}
        name: web
        ports:
        - containerPort: 8080
        resources: {}
status: {}
