apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-payment
    projectName: {{ .Values.labels.projectName }}
  name: deploy-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-payment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-payment
    spec:
      containers:
      - image: {{ .Values.image.repo}}/payment:{{ .Values.image.version}}
        name: payment
        ports:
        - containerPort: 8080
        resources: {}
status: {}
