apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-mongo
    projectName: {{ .Values.labels.projectName }}
  name: deploy-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-mongo
    spec:
      containers:
      - image: {{ .Values.image.repo}}/mongo:{{ .Values.image.version }}
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
status: {}
