apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-user
    projectName: {{ .Values.labels.projectName }}
  name: user
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: deploy-user
status:
  loadBalancer: {}
