apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-web
    projectName: {{ .Values.labels.projectName }}
  name: web
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: deploy-web
status:
  loadBalancer: {}
