apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-mongo
    projectName: {{ .Values.labels.projectName }}
  name: mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: deploy-mongo
status:
  loadBalancer: {}
