apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-redis
    projectName: {{ .Values.labels.projectName }}
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: deploy-redis
status:
  loadBalancer: {}
