apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-ratings
    projectName: {{ .Values.labels.projectName }}
  name: ratings
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deploy-ratings
status:
  loadBalancer: {}
