apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-mysql
    projectName: {{ .Values.labels.projectName }}
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: deploy-mysql
status:
  loadBalancer: {}
