apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-payment
    projectName: {{ .Values.labels.projectName }}
  name: payment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: deploy-payment
status:
  loadBalancer: {}
