apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-mysql
  name: deploy-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-mysql
    spec:
      containers:
      - image: riyadorkadi/project1-mysql:v1
        name: project1-mysql
        ports:
        - containerPort: 3306
        resources: {}
status: {}
