apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-shipping
  name: deploy-shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-shipping
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-shipping
    spec:
      containers:
      - image: riyadorkadi/project1-shipping:v1
        name: project1-shipping
        ports:
        - containerPort: 8080
        resources: {}
status: {}
