apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-user
  name: deploy-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-user
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-user
    spec:
      containers:
      - image: riyadorkadi/project1-user:v1
        name: project1-user
        ports:
        - containerPort: 8080
        resources: {}
status: {}
