apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-mongo
  name: deploy-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-mongo
    spec:
      containers:
      - image: riyadorkadi/project1-mongo:v1
        name: project1-mongo
        ports:
        - containerPort: 27017
        resources: {}
status: {}
