apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-catalogue
  name: catalogue
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: deploy-catalogue
status:
  loadBalancer: {}
