apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-shipping
  name: shipping
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: deploy-shipping
status:
  loadBalancer: {}
